#!/usr/bin/python
# -*- coding:utf-8 -*-

from   model    import database
from   query    import station
from   query    import train
import argparse
import sys
import os

# Create the top-level parser
parser = argparse.ArgumentParser(description='SNAIL : Horaires des trains')
parser.add_argument('-v', '--verbose', action='store_true', help='verbose')
parser.add_argument('--no-color', action='store_true', help='with color')
subparser = parser.add_subparsers(title='commands', dest="command_name" )

# Create the parser for the "init" command
parser_init = subparser.add_parser('init', help='create, init the database')
parser_init.add_argument('url', action='store', help='url of web-service used to init the database')

# Create the parser for the "station" command
parser_station = subparser.add_parser('station', help='list stations')
parser_station.add_argument('names', action='store', nargs='*', help='names of the stations')

# Create the parser for the "train" command
parser_train = subparser.add_parser('train', help='list next trains on a station')
parser_train.add_argument('station', action='store', help='the DDG code of the station')

# Create the parser for the "help" command
parser_help = subparser.add_parser('help', help='help for a command')

args = parser.parse_args()

# Get the path to command from where she's called                           
path = "."
if os.path.islink(sys.argv[0]):
    path = os.readlink(sys.argv[0])[:-5]
else:
    path =  sys.argv[0][:-5]
path = os.path.abspath(path) + os.sep

# Command : init
if args.command_name == 'init':
    
    # The default database
    database_path = path + 'snail.sqlite'

    # Create the base
    database.create(database_path)

    # Init the base
    database.init(database_path, args.url)

# Command : station
elif args.command_name == 'station':

    # The default database
    database_path = path + 'snail.sqlite'

    # List the stations with {args.name} as part of her name
    station.list(database_path, args.names)

# Command : train
elif args.command_name == 'train':

    # The default database
    database_path = path + 'snail.sqlite'

    # The default parameters
    parameters_path = path + 'parameters.json'

    # List the trains
    train.list(database_path, parameters_path, args.station)

# No command : help
else:
    parser.print_help()







